# Generated by Django 3.1.12 on 2025-12-03 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('gaming', 'Gaming'), ('music', 'Música'), ('talk', 'Xerrades'), ('education', 'Educació'), ('sports', 'Esports'), ('entertainment', 'Entreteniment'), ('technology', 'Tecnologia'), ('art', 'Art i Creativitat'), ('other', 'Altres')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_viewers',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduled_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programat'), ('live', 'En Directe'), ('finished', 'Finalitzat'), ('cancelled', 'Cancel·lat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='stream_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='events/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
