# Generated by Django 3.1.12 on 2026-01-06 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20251203_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('gaming', 'Gaming'), ('music', 'Música'), ('talk', 'Xerrades'), ('education', 'Educació'), ('sports', 'Esports'), ('entertainment', 'Entreteniment'), ('technology', 'Tecnologia'), ('art', 'Art i Creativitat'), ('other', 'Altres')], max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creat el'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Descripció'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='És destacat?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_viewers',
            field=models.PositiveIntegerField(default=100, verbose_name="Màxim d'espectadors"),
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduled_date',
            field=models.DateTimeField(verbose_name='Data programada'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programat'), ('live', 'En Directe'), ('finished', 'Finalitzat'), ('cancelled', 'Cancel·lat')], default='scheduled', max_length=20, verbose_name='Estat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stream_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL del Streaming'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='Etiquetes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, default='events/default_thumbnail.jpg', null=True, upload_to='events/thumbnails/', verbose_name='Imatge de portada'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Títol'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualitzat el'),
        ),
    ]
